name: Archive Recorded Meeting

description: |
  Archive a recorded meeting in the Edge Foundation team repository.

assignees:
  - "@Copilot"

body:
  - type: input
    attributes:
      label: Meeting
      description: The name of the meeting or subject covered.
    validations:
      required: true

  - type: input
    attributes:
      label: Date
      description: In ISO format (YYYY-MM-DD) please.
    validations:
      required: true

  - type: input
    attributes:
      label: URL
      description: The URL of the recorded meeting.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Prompt
      description: Default Copilot Prompt. Leave as is.
      value: |
        Dear AI Overloard, please do crap for me.
